# Vaccination

## Vaccines

### Definitions

A vaccine is a biological product that can be used to safely induce an **immune response** that confers protection against infection and/or disease on subsequent exposure to a pathogen [@pollard2021].



### Classification

Over the past few decades, new vaccine platforms have been developed including viral vectors, nucleic acid-based RNA and DNA vaccines, and virus-like particles. However, traditionally vaccines are classified as live or non-live:

1.  Live:

-   Are developed so that, in an immunocompetent host, they replicate sufficiently to produce a strong immune response, but not so much as to cause significant disease manifestations.

-   Trade-off between strong immune response and avoid symptomatic disease, therefore some live attenuated vaccines require multiple doses and induce relatively short-lived immunity. For example, 5% of children will develop a rash and up to 15% fever after measles vaccination

-   Potentially replicate in an uncontrolled manner in immuno-compromised individuals.

-   Examples: measles, mumps, rubella and rotavirus, oral polio vaccine, the Mycobacterium bovis bacillus Calmette–Guérin (BCG) vaccine for TB and live attenuated influenza vaccine

2.  Non-live: no risk to immunocompromised individuals (although may not confer protection in those with B cell or combined immunodeficiency).

B cells

-   Produce antibodies (**humoral** immunity).

T cells

-   Directly attack infected cells (**cellular** immunity).

1.  Killer (cytotoxic):

2.  Helper: subtypes by profiles of cytokine production

## Innate vs adaptive immune system

## Prevent infection vs disease

Some evidence showed that BCG vaccine can prevent both infection and disease [@pollard2021].

- Infection: BCG-vaccinated children had a memory T-cell response to infection, as indicated by a positive interferon-$\gamma$ release assay.
- Disease: BCG vaccination reduces the spread of *M. tuberculosis* bacteria in the blood, mediated by T-cell immunity.

## Non-specific effects

Measles disease casts a prolonged ‘shadow’ over the immune system, with depletion of existing immune memory, such that children who have had the disease have an increased risk of death from other causes over the next few years [@pollard2021].

## Factors affecting vaccine protection

- Maternal antibody levels
- Prior antigen exposure
- Age of vaccination
- Vaccine schedule
- Vaccine dose: intradermal vaccination has been shown to be immunogenic at much lower (fractional) doses than intramuscular vaccination for influenza, rabies and HBV vaccines [@pollard2021].



