project:
  type: book
  output-dir: docs

book:
  favicon: logo-icon.svg
  google-analytics: "G-X391ZN63GG"
  title: "Infectious disease modelling for babies"
  author:
    - name: Thinh Ong
      url: https://drthinhong.com/
      orcid: 0000-0001-6772-9291
  date: "05/22/2024"
  sidebar:
    collapse-level: 1
  chapters:
    - index.qmd
    - mod.qmd
    - part: det.qmd
      chapters: 
        - sir-det.qmd
        - seir-det.qmd
        - het-det.qmd
        - tsir.qmd
    - part: sto.qmd
      chapters:
        - seir-sto.qmd
    - part: calib.qmd
      chapters:
        - lse.qmd
        - mle.qmd
        - mcmc.qmd
        - pf.qmd
    - part: rnum.qmd
      chapters:
        - gen-int.qmd
        - r0.qmd
        - rt.qmd
        - rt-prac.qmd
    - part: intv.qmd
      chapters: 
        - ftc.qmd
        - vax.qmd
        - vax-perf.qmd
        - vax-mod.qmd
        - vax-measles.qmd
    - part: he.qmd
      chapters:
        - he-etr.qmd
    - part: sero.qmd
      chapters: 
        - serocat.qmd
    - part: stat-mod.qmd
      chapters: 
        - glm.qmd
        - gam.qmd
        - surv.qmd
        - bayes.qmd
    - part: rp.qmd
      chapters: 
        - rp-risk.qmd
        - rp-response.qmd
    - references.qmd
  appendices:
    - dict.qmd
    - odin.qmd
    - metaprg.qmd
    - func.qmd
    - simll.qmd

bibliography: references.bib
csl: apa.csl

format:
  html:
    theme: [cosmo, theme.scss]
    code-overflow: wrap
    code-copy: true
    fig-format: svg
    df-print: paged
    toc-depth: 5
    toc-expand: 3
    callout-appearance: simple

comments:
  giscus:
    repo: thinhong/idm4b

