project:
  type: book
  output-dir: docs

book:
  title: "Modelling"
  author: "Thinh Ong"
  date: "22/05/2024"
  chapters:
    - index.qmd
    - part: det.qmd
      chapters: 
        - sir-det.qmd
        - tsir.qmd
    - part: sto.qmd
      chapters: 
        - sir-sto.qmd
    - references.qmd

bibliography: references.bib
csl: nature.csl

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



