project:
  type: book
  output-dir: docs
  execute-dir: project

book:
  favicon: assets/logo-icon.svg
  google-analytics: "G-X391ZN63GG"
  title: "Infectious disease modelling for babies"
  author:
    - name: Thinh Ong
      url: https://drthinhong.com/
      orcid: 0000-0001-6772-9291
  date: "05/22/2024"
  sidebar:
    collapse-level: 1
  chapters:
    - index.qmd
    - mod.qmd
    - part: det/index.qmd
      chapters:
        - det/sir.qmd
        - det/seir.qmd
        - det/het.qmd
        - det/tsir.qmd
    - part: sto/index.qmd
      chapters:
        - sto/sir.qmd
        - sto/seir.qmd
        - sto/ar.qmd
        - sto/branch-proc.qmd
    - part: fit/index.qmd
      chapters:
        - fit/lse.qmd
        - fit/lik.qmd
        - fit/mle.qmd
        - fit/mcmc.qmd
        - fit/pmcmc.qmd
    - part: sel/index.qmd
      chapters:
        - sel/cv.qmd
    - part: rnum/index.qmd
      chapters:
        - rnum/gen-int.qmd
        - rnum/r0.qmd
        - rnum/rt.qmd
        - rnum/rt-prac.qmd
    - part: intv/index.qmd
      chapters:
        - intv/ftc.qmd
        - intv/vax.qmd
        - intv/vax-perf.qmd
        - intv/vax-mod.qmd
        - intv/vax-measles.qmd
    - part: he/index.qmd
      chapters:
        - he/etr.qmd
    - part: sero/index.qmd
      chapters:
        - sero/cat.qmd
    - part: stat/index.qmd
      chapters:
        - stat/glm.qmd
        - stat/gam.qmd
        - stat/nlin.qmd
        - stat/surv.qmd
        - stat/bayes.qmd
        - stat/ts.qmd
    - references.qmd
  appendices:
    - appx/dict.qmd
    - appx/math.qmd

bibliography: references.bib
csl: apa.csl

execute:
  freeze: auto

format:
  html:
    theme: [cosmo, assets/theme.scss]
    include-in-header: assets/head-fonts.html
    css: assets/tokens.css
    code-copy: true
    code-overflow: wrap
    fig-format: svg
    df-print: paged
    toc-depth: 5
    toc-expand: 3
    callout-appearance: simple

comments:
  giscus:
    repo: thinhong/idm4b
    repo-id: R_kgDOL-8Pvg
