project:
  type: book
  output-dir: docs

book:
  google-analytics: "G-X391ZN63GG"
  title: "Infectious disease modelling for babies"
  author:
    - name: Thinh Ong
      url: https://drthinhong.com/
      orcid: 0000-0001-6772-9291
  date: "05/22/2024"
  chapters:
    - index.qmd
    - epith.qmd
    - part: det.qmd
      chapters: 
        - sir-det.qmd
        - tsir.qmd
    - part: sto.qmd
      chapters: 
        - sir-sto.qmd
    - part: calib.qmd
      chapters: 
        - pomp.qmd
    - part: rp.qmd
      chapters: 
        - rp-risk.qmd
    - references.qmd

bibliography: references.bib
csl: apa.csl

format:
  html:
    theme: cosmo
    code-overflow: wrap

comments:
  giscus:
    repo: thinhong/idm4b

