project:
  type: book
  output-dir: docs
  
execute:
  freeze: auto

book:
  favicon: logo-icon.svg
  google-analytics: "G-X391ZN63GG"
  title: "Infectious disease modelling for babies"
  author:
    - name: Thinh Ong
      url: https://drthinhong.com/
      orcid: 0000-0001-6772-9291
  date: "05/22/2024"
  sidebar:
    collapse-level: 1
  chapters:
    - index.qmd
    - mod.qmd
    - part: det.qmd
      chapters: 
        - sir-det.qmd
        - seir-det.qmd
        - tsir.qmd
    - part: sto.qmd
      chapters: 
        - seir-sto.qmd
    - part: calib.qmd
      chapters: 
        - lse.qmd
        - mle.qmd
        - mcmc.qmd
        - pomp.qmd
    - part: rnum.qmd
      chapters:
        - gen-int.qmd
        - r0.qmd
        - rt.qmd
    - part: intv.qmd
      chapters: 
        - ftc.qmd
    - part: vax.qmd
      chapters:
        - vax-perf.qmd
        - vax-mod.qmd
    - part: he.qmd
      chapters:
        - he-etr.qmd
    - part: rp.qmd
      chapters: 
        - rp-risk.qmd
    - references.qmd
  appendices:
    - dict.qmd
    - func.qmd

bibliography: references.bib
csl: apa.csl

format:
  html:
    theme: [cosmo, theme.scss]
    code-overflow: wrap
    code-copy: true
    fig-format: svg
    df-print: paged
    toc-depth: 5
    toc-expand: 3

comments:
  giscus:
    repo: thinhong/idm4b

