# Epidemic theory

## Growth rate $r$ and reproduction number $R$

Growth rate $r$ and reproduction number $R$ are basically the same. $r$ is used in continuous time and $R$ is used in discrete time.

### Growth rate $r$

The rate at which new cases are arising[@anderson2020]. It can be a positive number (new infections is increasing) or a negative number (new infections is decreasing).

The number of new infections at an increasing or decreasing exponential rate. It is dependent on the reproduction number and timescale between infections.

$$\frac{d_\text{newCases}}{dt}$$

### Reproduction number $R$



#### Basic reproduction number $R_0$

$R_0$ is the **average** number of **secondary cases** generated by **an average infected person** throughout their **infectious period** in a **wholly susceptible population**[@anderson2020].

#### Effective reproduction number $R_e$

$R_e$ is the **average** number of **secondary cases** generated by **an average infected person** throughout their **infectious period** in a population (not sure, edit later).

$$R_e = s \times R_0$$

#### Effective reproduction number at time $t$ $R_t$

$R_t$ is the average number of secondary cases generated by one infected person at time $t$ during the epidemic.


