# Preface {.unnumbered}

Last modified: {{< now "%B %d, %Y" >}}.

This book brings together everything I have learned about infectious disease modelling during my PhD journey. Special thanks to my idol, [Dr. James Hay](https://uk.linkedin.com/in/james-a-hay), who once gave these genius advice:

> "Read and learn now - it will be harder later on."
>
> "Spent a lot of time writing well-documented, generalisable code that didn't necessarily turn into publications at the time. I now use that code **all of the time**."
>
> Dr. James Hay's inspiring talk at the MIDSEA ECR April 2024 Meeting.

These words encouraged me to read and learn more, and to ensure every detail was carefully documented. In this book, you (and my future self) will find:

-   Methodologies for mathematical models of infectious diseases.
-   A dictionary of jargon with cited definitions.
-   Step-by-step guides for writing infectious disease reports, following the Center for Disease Control and Prevention report format: data, workflow, analyses, and inference.

The content of this book is based on the materials I digested during my PhD, with specific articles and readings cited throughout the text. I am deeply grateful to my PhD supervisors, Dr. Marc Choisy, A/Prof. Louise Thwaites, Dr. Hugo Turner, for their caring, inspiring, and enthusiastic guidance. My most heartfelt thanks also go to my mentors, A/Prof. Le Van Tan, A/Prof. Wirichada Pan-Ngum, Asst Prof. Kiesha Prem, Dr. Phung Khanh Lam, and Dr. Leigh Jones, for always nurturing and guiding me towards the best path.

I would like to acknowledge the following educational experiences:

+-------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Course                                                                                          | Lecturers                                                                                                                                                         | Institutions                                                                                                                                                                         |
+=================================================================================================+===================================================================================================================================================================+======================================================================================================================================================================================+
| Modelling Infectious Diseases in South East Asia (MIDSEA) Summer School (2024)                  | Modelling Master Class: Prof. Alex Cook; Prof. Jomar Fajardo Rabajante; Prof. Wirichada Pan-Ngum                                                                  | National University of Singapore; Mahidol Oxford Research Unit; Oxford University Clinical Research Unit; University of the Philippines; De La Salle Manila; Mahasarakham University |
|                                                                                                 |                                                                                                                                                                   |                                                                                                                                                                                      |
|                                                                                                 | Modelling interventions and Health economic evaluation: Asst/Prof. Kiesha Prem; Asst/Prof. Hannah Clapham; Asst/Prof. Swapnil Mishra; Asst/Prof. Thitiya Theparod |                                                                                                                                                                                      |
+-------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Summer Institute in Statistics and Modeling in Infectious Diseases (SISMID) (2023)              | Stochastic Epidemic Models with Inference: Prof. Tom Britton; Prof. Ira M Longini                                                                                 | University of Washington                                                                                                                                                             |
|                                                                                                 |                                                                                                                                                                   |                                                                                                                                                                                      |
|                                                                                                 | MCMC I: Prof. M. Elizabeth Halloran; Prof. Volodymyr Minin; Prof. Kari Auranen                                                                                    |                                                                                                                                                                                      |
|                                                                                                 |                                                                                                                                                                   |                                                                                                                                                                                      |
|                                                                                                 | MCMC II: Prof. Philip O'Neill; Prof. Theodore Kypraios                                                                                                            |                                                                                                                                                                                      |
|                                                                                                 |                                                                                                                                                                   |                                                                                                                                                                                      |
|                                                                                                 | Simulation-Based Inference for Epidemiological Dynamics: Prof. Aaron King; Prof. Edward Ionides                                                                   |                                                                                                                                                                                      |
+-------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Introduction to mathematical models of the Epidemiology & Control of Infectious Diseases (2022) | Prof. Azra Ghani; Prof. Alex Cook; Dr. Lilith Whittles; Dr. Clare McCormack; Dr. Tara Mangal; Dr. Juliette Unwin                                                  | Imperial College London; Nanyang Technological University                                                                                                                            |
+-------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Mathematical Modelling for Vaccine-preventable Diseases (2022)                                  | Prof. Caroline Trotter; Prof. Julia Gog; Prof. Nik Cunniffe; Prof. Thumbi Mwanga; A/Prof. Andrew Conlan; Dr. Cerian Webb; Dr. Katy Gaythorpe; Dr. Matt Castle     | Vaccine Impact Modelling Consortium; University of Cambridge                                                                                                                         |
+-------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
: {tbl-colwidths="[30,40,30]" .hover}

Many thanks to the authors who kindly shared materials in response to my inquiries on these topics:

-   Workshop: Modeling Rabies Outbreak and Control (2023), by Dr. Phrutsamon Wongnak.

If you enjoyed this book or found any mistakes, please leave a comment below. Your feedback means a lot!
