# Estimating $R_t$

## Potential biases

$R_t$ is a **value** in specific **time**, therefore there are 2 potential forms of bias in $R_t$ estimates [@gostic2020]:

-   **Accuracy** (the value): Systematic over- or underestimation caused by misspecification of the generation interval. Mostly impact when $R_t$ is substantially \> 1 (e.g., the beginning of COVID-19 when $R_t$ is relatively high) or \< 1 (e.g., after a very effective intervention then $R_t$ might be low).

-   **Timeliness** (the time): Temporal inaccuracy that $R_t$ estimates may be leading or lagging the true date, has several possible causes and can be difficult to avoid.

Generation interval: sum of residence times in compartments E and I [@gostic2020].

## Methods

$R_t$ can be defined in 2 ways: as the **instantaneous reproduction number** (see @sec-rt-inst) or as the **case reproduction number** (see @sec-rt-case).

### Instantaneous reproduction number $R_t^i$

::: {#def-rt-inst}
The instantaneous reproduction number is the expected number of secondary infections occurring at time $t$, divided by the number of infected individuals, each scaled by their relative infectiousness at time $t$ (an individual’s relative infectiousness is based on the generation interval and time since infection) [@gostic2020].
:::

#### Exact calculation

For a compartmental model (SIR or SEIR), $R_t^i$ can be calculated exactly as:

$$R_t^i = \beta(t) S(t) D$$

- $\beta(t)$: the time-varying transmission rate.
- $S(t)$: the fraction of the population that is susceptible.
- $D$: the mean duration of infectiousness.

#### Cori method

Cori and colleagues estimates $R_t^i$ as [@gostic2020]:

$$R_t^i = \frac{I_t}{\sum_{s = 1}^{t} I_{t - s} w_s}$$

- $I_t$: the number of infection on day $t$.
- $I_{t - s}$: the number of individuals who became infected $s$ days in the past.
- $w_s$: the generation interval, or the probability that $s$ days separate the moment of infection in an index case and a daughter case.
- $I_{t - s} w_s$: we scale the number of individuals who became infected $s$ days in the past by how infectiousness are they still on day $t$ (which is $s$ days after the date they got infected, $w_s$).

Looking back at @def-rt-inst, $R_t^i$ is the expected number of secondary infections occurring at time $t$ ($I_t$), divided by the number of infected individuals ($\sum_{s = 1}^{t} I_{t - s}$), each scaled by their relative infectiousness at time $t$ ($w_s$).

The only parametric assumption required by this method is **the form of the generation interval**. The standard assumption is that $w_s$ follows a **discretized gamma distribution**, but any parametric or empirical discrete distribution also work [@gostic2020].

### Case reproduction number $R_t^c$

::: {#def-rt-case}
The case or cohort reproduction number is the expected number of secondary infections that an individual who becomes infected at time $t$ will eventually cause as they progress through their infection.
:::

#### Exact calculation

$$R_t^c = \int_{u = t}^{\infty} R_u^i w_{u-t} du$$

- $R_u^i$: the instantaneous reproduction number of current infected cases at time $u$, starting from $t$ to the end of their infectious period $\infty$.
- $w_{u-t}$: the infectiousness of them at that time.

#### Wallinga and Teunis method

**Step 1**. Estimate the likelihood that case $j$ (infected at time $t_j$) infected case $i$ (at time $t_i$).

$$p_{ij} = \frac{w_{t_i - t_j}}{\sum_{i \neq k} w_{t_i - t_k}}$$

- $\sum_{i \neq k} w_{t_i - t_k}$: sum of the infectiousness of all cases (other than $i$) infects case $i$.

**Step 2**. Compute the individual reproduction number of case j.

$$R_j = \sum_i p_{ij}$$

**Step 3**. Compute the case reproduction number at time $t$, it is the expected value of $R_j$ for all individuals infected at time $t$.

$$R_t^c = \mathbb{E}(R_j)$$

## Code

### EpiNow2
